Json file uploader
flux-labs/flux-uploader pull request #7
Opened 2016-10-12 01:00 UTC by david733

A number of changes to allow loading and uploading of .json files. Integrates Ace Editor to preview the JSON contents.

2016-10-13 20:37 UTC, kylegmaxwell requested changes
ok, nice work, this is working, but just a few small things to fix.

2016-10-13 20:37 UTC, kylegmaxwell commented on index.html
> -  <!-- Google Analytics -->
Why did you remove this, are we using different analytics now?

2016-10-13 20:37 UTC, kylegmaxwell commented on lib/ace/ext-beautify.js
> +ace.define("ace/ext/beautify/php_rules",["require","exports","module","ace/token_iterator"], function(require, exports, module) {
Are you actually using all these extensions? I would prefer to see just the ace editor minified file and maybe a couple config files, not 27 new files.

2016-10-13 20:37 UTC, kylegmaxwell commented on src/converters.js
> +      let json = JSON.parse(inJson);
Don't use let unless you are using babel

2016-10-13 20:37 UTC, kylegmaxwell commented on src/converters.js
> +    } catch (e) {
I don't think you need try catch here. The exception will automatically cause the promise to reject.

2016-10-13 20:37 UTC, kylegmaxwell commented on README.md
> +1. From command line in the flux-uploader folder, run npm install express
You can just say 'npm install', not 'npm install express', express is already specified as a dependency in package.json.

2016-10-19 00:07 UTC, david733 commented on index.html
> -  <!-- Google Analytics -->
Yes, this was a requested change by Javier.

2016-10-19 00:07 UTC, david733 commented on lib/ace/ext-beautify.js
> +ace.define("ace/ext/beautify/php_rules",["require","exports","module","ace/token_iterator"], function(require, exports, module) {
Removed all but one of the extensions, replaced remaining with minified versions.

2016-10-19 00:09 UTC, david733 commented on src/converters.js
> +      let json = JSON.parse(inJson);
fixed

2016-10-19 00:09 UTC, david733 commented on src/converters.js
> +    } catch (e) {
removed try catch

2016-10-19 00:10 UTC, david733 commented on README.md
> +1. From command line in the flux-uploader folder, run npm install express
fixed

2016-10-19 00:25 UTC, david733 commented
Thanks Kyle! Merging to master.

2016-10-19 00:26 UTC, merged